#!/bin/sh
set -e
if [ "$1" = remove ] && [ -d /run/systemd/system ]; then
    for s in backuppc-client backuppc-client-tun; do
        systemctl disable --now "$s.service" >/dev/null 2>&1 || true
    done
fi
exit 0
