// Proto-контракт outbound-протокола backuppc для ядра Xray.
//
// Конфиг передается в core.OutboundHandlerConfig.ProxySettings
// (serial.TypedMessage) и материализуется registered-креатором из
// пакета core/outbound. Полное имя сообщения: backuppc.Config.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: backuppc.proto

package backuppcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config — настройки одного backuppc-outbound (соответствует
// backuppc.ClientConfig транспортной библиотеки).
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address — адрес сервера xray-backuppc (хост[:порт], домен или IP).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// port — TLS-порт сервера (обычно 443).
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// uuid — ключ клиента: HMAC несущего канала + VLESS-аутентификация.
	Uuid string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// host — домен-донор для Host-заголовка (SNI подменяется этим же значением).
	Host string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// endpoint_paths — список несущих методов backuppc.* (ротация на чанк).
	EndpointPaths []string `protobuf:"bytes,5,rep,name=endpoint_paths,json=endpointPaths,proto3" json:"endpoint_paths,omitempty"`
	// user_agent — User-Agent пула BackupPC (пусто — случайный из пула).
	UserAgent string `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// insecure — пропустить верификацию TLS (только тесты).
	Insecure bool `protobuf:"varint,7,opt,name=insecure,proto3" json:"insecure,omitempty"`
	// cert_fingerprint — SHA-256 (hex) сертификата сервера: пиннинг вместо CA.
	CertFingerprint string `protobuf:"bytes,8,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	// min_padding / max_padding — диапазон случайного паддинга кадров (байты).
	MinPadding uint32 `protobuf:"varint,9,opt,name=min_padding,json=minPadding,proto3" json:"min_padding,omitempty"`
	MaxPadding uint32 `protobuf:"varint,10,opt,name=max_padding,json=maxPadding,proto3" json:"max_padding,omitempty"`
	// session_duration_ms — целевое время жизни сессии-чанка (мс).
	SessionDurationMs int64 `protobuf:"varint,11,opt,name=session_duration_ms,json=sessionDurationMs,proto3" json:"session_duration_ms,omitempty"`
	// session_bytes — лимит чанка по объему (байты).
	SessionBytes int64 `protobuf:"varint,12,opt,name=session_bytes,json=sessionBytes,proto3" json:"session_bytes,omitempty"`
	// ping_base_ms — базовый интервал keep-alive心跳 (мс).
	PingBaseMs int64 `protobuf:"varint,13,opt,name=ping_base_ms,json=pingBaseMs,proto3" json:"ping_base_ms,omitempty"`
	// ping_jitter_ms — разброс jitter keep-alive (мс).
	PingJitterMs int64 `protobuf:"varint,14,opt,name=ping_jitter_ms,json=pingJitterMs,proto3" json:"ping_jitter_ms,omitempty"`
	// balancing_interval_ms — интервал балансировщика rx/tx (мс).
	BalancingIntervalMs int64 `protobuf:"varint,15,opt,name=balancing_interval_ms,json=balancingIntervalMs,proto3" json:"balancing_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_backuppc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_backuppc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_backuppc_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Config) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Config) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Config) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Config) GetEndpointPaths() []string {
	if x != nil {
		return x.EndpointPaths
	}
	return nil
}

func (x *Config) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Config) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Config) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *Config) GetMinPadding() uint32 {
	if x != nil {
		return x.MinPadding
	}
	return 0
}

func (x *Config) GetMaxPadding() uint32 {
	if x != nil {
		return x.MaxPadding
	}
	return 0
}

func (x *Config) GetSessionDurationMs() int64 {
	if x != nil {
		return x.SessionDurationMs
	}
	return 0
}

func (x *Config) GetSessionBytes() int64 {
	if x != nil {
		return x.SessionBytes
	}
	return 0
}

func (x *Config) GetPingBaseMs() int64 {
	if x != nil {
		return x.PingBaseMs
	}
	return 0
}

func (x *Config) GetPingJitterMs() int64 {
	if x != nil {
		return x.PingJitterMs
	}
	return 0
}

func (x *Config) GetBalancingIntervalMs() int64 {
	if x != nil {
		return x.BalancingIntervalMs
	}
	return 0
}

var File_backuppc_proto protoreflect.FileDescriptor

const file_backuppc_proto_rawDesc = "" +
	"\n" +
	"\x0ebackuppc.proto\x12\bbackuppc\"\xfe\x03\n" +
	"\x06Config\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12%\n" +
	"\x0eendpoint_paths\x18\x05 \x03(\tR\rendpointPaths\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12\x1a\n" +
	"\binsecure\x18\a \x01(\bR\binsecure\x12)\n" +
	"\x10cert_fingerprint\x18\b \x01(\tR\x0fcertFingerprint\x12\x1f\n" +
	"\vmin_padding\x18\t \x01(\rR\n" +
	"minPadding\x12\x1f\n" +
	"\vmax_padding\x18\n" +
	" \x01(\rR\n" +
	"maxPadding\x12.\n" +
	"\x13session_duration_ms\x18\v \x01(\x03R\x11sessionDurationMs\x12#\n" +
	"\rsession_bytes\x18\f \x01(\x03R\fsessionBytes\x12 \n" +
	"\fping_base_ms\x18\r \x01(\x03R\n" +
	"pingBaseMs\x12$\n" +
	"\x0eping_jitter_ms\x18\x0e \x01(\x03R\fpingJitterMs\x122\n" +
	"\x15balancing_interval_ms\x18\x0f \x01(\x03R\x13balancingIntervalMsB\x1aZ\x18backuppc-core/backuppcpbb\x06proto3"

var (
	file_backuppc_proto_rawDescOnce sync.Once
	file_backuppc_proto_rawDescData []byte
)

func file_backuppc_proto_rawDescGZIP() []byte {
	file_backuppc_proto_rawDescOnce.Do(func() {
		file_backuppc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backuppc_proto_rawDesc), len(file_backuppc_proto_rawDesc)))
	})
	return file_backuppc_proto_rawDescData
}

var file_backuppc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_backuppc_proto_goTypes = []any{
	(*Config)(nil), // 0: backuppc.Config
}
var file_backuppc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backuppc_proto_init() }
func file_backuppc_proto_init() {
	if File_backuppc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backuppc_proto_rawDesc), len(file_backuppc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backuppc_proto_goTypes,
		DependencyIndexes: file_backuppc_proto_depIdxs,
		MessageInfos:      file_backuppc_proto_msgTypes,
	}.Build()
	File_backuppc_proto = out.File
	file_backuppc_proto_goTypes = nil
	file_backuppc_proto_depIdxs = nil
}
